# Site
repository: georgiosbounias/modern-resume-theme
favicon: images/8. ΦΩΤΟΓΡΑΦΙΑ ΤΥΠΟΥ ΤΑΥΤΟΤΗΤΑΣ - ΜΠΟΥΝΙΑΣ ΓΕΩΡΓΙΟΣ.jpg

# Content configuration version
version: 2

# Personal info
name: Γεώργιος Μπουνιάς
title: Μεταπτυχιακός Φοιτητής Τμήματος Πληροφορικής
email: inf.dig2113@ionio.gr

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  georgiosbounias
instagram_username: georgecorfu1986

# About Section
# about_title: Σχετικά με μένα
about_profile_image: images/8. ΦΩΤΟΓΡΑΦΙΑ ΤΥΠΟΥ ΤΑΥΤΟΤΗΤΑΣ - ΜΠΟΥΝΙΑΣ ΓΕΩΡΓΙΟΣ.jpg
about_content: | # this will include new lines to allow paragraphs
  Ονομάζομαι Μπουνιάς Γεώργιος, είμαι μαθηματικός και εργάζομαι σε λογιστικό γραφείο.

content:
  - title: Επαγγελματική εμπειρία # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Λογιστικό Φοροτεχνικό Γραφείο "Βρανίκα Κ. Χριστίνα"
        sub_title: Υπεύθυνος Τμήματος Μισθοδοσίας
        caption: Σεπτέμβριος 2017 - Σήμερα
        description: | # this will include new lines to allow paragraphs
            -Υπεύθυνος υπολογισμού και έκδοσης μισθοδοσίας και λοιπών εργασιακών υποθέσεων.

  - title: Εκπαίδευση # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Πανεπιστήμιο Πατρών
        caption: 2004 - 2011
        sub_title: Πτυχίο Σχολής Μαθηματικών
        description: | # this will include new lines to allow paragraphs
          Βαθμός Πτυχίου: 6,32 Ημερομηνία περάτωσης σπουδών: 1/3/2011

  - title: Δραστηριότητες
    layout: text
    content: | # this will include new lines to allow paragraphs
    ΣΩΜΑ ΕΛΛΗΝΙΚΟΥ ΟΔΗΓΙΣΜΟΥ
	  Ενεργό στέλεχος από το 2013
	  Αρχηγός Ομάδας παιδιών Ηλικίας 7-11 ετών (2017-2020)
	  Συμμετοχή και διοργάνωση κατασκηνώσεων από το 2013

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
